# Use an official Go runtime as a parent image
FROM golang:latest AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module definition file
COPY go.mod go.sum ./

COPY farm/ .
COPY mqtt/ .

# Download Go module dependencies
RUN go mod download -x

# Build the Go application for the farm controller
RUN go build -o farm_controller farm_control.go

CMD ["./farm_controller"]