
FROM golang:1.24-alpine AS builder

RUN apk add --no-cache gcc libc-dev

ENV CGO_ENABLED=1

WORKDIR /app/

COPY go.mod go.sum ./

COPY site/ .

RUN go mod download -x


EXPOSE 8080
CMD ["go", "run", "."]

