networks:
  farm-network:

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mos1
    networks:
      - farm-network
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /etc/mosquitto/conf.d/listeners.conf:/mosquitto/config/mosquitto.conf
      
  webcam:
    build:
      context: .
      dockerfile: Dockerfile.webcam
    container_name: webcam
    networks:
      - farm-network
    ports:
      - "8081:8081"
    depends_on:
      - mosquitto
    privileged: true

  farmcontrol:
    build:
      context: .
      dockerfile: Dockerfile.farmcontrol
    container_name: farmcontrol
    networks:
      - farm-network
    volumes:
      - type: bind
        source: /home/mike/Documents/Gofarm/farm/sensor_data.db
        target: /app/sensor_data.db
        read_only: false
    depends_on:
      - mosquitto
    privileged: true

volumes:
  farmcontrol_instance: