FROM golang:1.24-alpine AS dev

RUN apk add --no-cache gcc musl-dev

WORKDIR /app/website

COPY go.mod go.sum ./

RUN go mod download -x

# CMD ["tail", "-f", "/dev/null"]
# CMD [".app/website/cmd/web", "-dsn", "app/website/cmd/web/instance/snippets.db"]

